### ISSUE TITLE
No function variables show in schema

### ISSUE THREAD

**Issue by sheerun** [sheerun/graphqlviz#1]
I just noticed there are no variable names in function output.

I'll look into it, but maybe @NathanRSmith you'd like to fix it in your spare time?

**Comment by NathanRSmith** [comment]
Do you mean field arguments?

**Comment by NathanRSmith** [comment]
http://facebook.github.io/graphql/#sec-Language.Arguments ?

**Comment by sheerun** [comment]
Yes, exactly

**Comment by NathanRSmith** [comment]
I'll take a stab at it

**Comment by NathanRSmith** [comment]
Fields with a lot of args could get unwieldy, but I think this will suffice.

**Comment by sheerun** [comment]
Great :) I've updated changelog and released it. Macroz/GraphQLviz prints field arguments on connections. https://camo.githubusercontent.com/b9c287bfac49bd0997ab7db748af18b7c00e6f66/68747470733a2f2f7261776769742e636f6d2f4d6163726f7a2f4772617068514c76697a2f6d61737465722f6578616d706c65732f646967697472616e7369742e737667

**Comment by NathanRSmith** [comment]
I like the current layout, but we could start having different renderers for different layouts after processing all the entities.

**Comment by NathanRSmith** [comment]
See #2 for multiple layouts.
