### ISSUE TITLE
Union support?

### ISSUE THREAD

**Issue by diaconesq** [sheerun/graphqlviz#10]
I love the idea of this project! 

I played with it a  bit on my GraphQL endpoint and it seems it doesn't support union types. Should it (and I'm missing something), or is the support for unions missing?

**Comment by NathanRSmith** [comment]
There is currently no support for unions. A pull request would certainly be welcome. I haven't messed with unions much, so maybe you have a concrete example?

**Comment by diaconesq** [comment]
Cool, I'll try to squeeze a bit of time and come up with a pull request.

**Comment by sheerun** [comment]
Fixed by #14
