### ISSUE TITLE
Show Input types and link to arguments.

### ISSUE THREAD

**Issue by rwe** [sheerun/graphqlviz#12]
This was noticed when creating sheerun/graphqlviz#11 because mutations typically have more complex input types. However, other elements such as connections and queries can refer to complex input types as well.

**Comment by ajs139** [comment]
I'm working on a branch to get this in:
https://github.com/ajs139/graphqlviz/tree/inputs
The outstanding work is to figure out the cli arguments (if any) to drive what should be shown (and if they should be colored differently).

**Comment by sheerun** [comment]
I've released @ajs139 changes, so this should work now with 2.0.0 :)
