### ISSUE TITLE
-bash: dot: command not found

### ISSUE THREAD

**Issue by TheMrugraj** [sheerun/graphqlviz#18]
I am getting below error
-bash: dot: command not found

**Comment by NathanRSmith** [comment]
The`dot` command comes from http://www.graphviz.org. Should be installable from most package managers.

**Comment by kenrim626** [comment]
First I attempted to install graphviz from the npm package manager:
`npm install -g graphviz`

When using the demo command that is shown in the readme file in this repository
`graphqlviz "http://localhost:9011/graphlq" | dot -Tpng | open -f -a Preview`
I got exactly the error that is described here. Even a restart could not fix this issue.

To ensure the path variables were setup correctly I then downloaded the *.msi file from http://www.graphviz.org and installed it manually. Afterwards the error still prevailed.

Do you have any additional information on what could be the problem and how to fix it?

**Comment by NathanRSmith** [comment]
I guess I should have been clearer. It should be installable from most *system* package managers (yum, apt, apk, brew, fink, etc). As for windows, I have no direct experience installing there, but make sure it is installed in your system path for the commands to be found. Alternatively you should be able to invoke the `dot.exe` from wherever it gets installed.

**Comment by kenrim626** [comment]
I added `C:\Program Files (x86)\Graphviz2.38\bin\` to the PATH-variable and it is now working correctly. Could you add the PATH-setup to the windows installer?

**Comment by NathanRSmith** [comment]
I added a blurb to the README. the `PATH` location will vary depending on which Graphviz version is installed.

**Comment by vp185184** [comment]
`brew install graphviz` on mac
