### ISSUE TITLE
Support multiple schema files

### ISSUE THREAD

**Issue by robross0606** [sheerun/graphqlviz#21]
Is it possible to feed multiple schema files (or perhaps a stream/pipe) to graphqlviz for situations where your schema is modularized?

**Comment by NathanRSmith** [comment]
Are you attempting to create multiple visualizations, one per schema, or combine multiple schemas into a single viz?

**Comment by robross0606** [comment]
One visualization from a modular schema (multiple files) without having to wrap everything in a script or creating an intermediate merged file.

**Comment by NathanRSmith** [comment]
Hmm, that's not currently a feature of the tool. I'm curious, are these schema parts representing multiple graphql endpoints that compose your application or is it a curated schema of parts composing a single graphql endpoint?

**Comment by NathanRSmith** [comment]
Stated another way, would the viz be multiple disjoined sub-graphs or are there links between the schema parts?

**Comment by robross0606** [comment]
The latter.  When schemas get large and cumbersome, there are tools and patterns out there for breaking up a single endpoint into multiple files for manageability.  Examples:

- GraphQL Modules: https://medium.com/the-guild/graphql-modules-feature-based-graphql-modules-at-scale-2d7b2b0da6da
- merge-graphql-schema: https://www.npmjs.com/package/merge-graphql-schemas

**Comment by NathanRSmith** [comment]
Interesting, you could always introspect the whole combined schema, but it sounds like you'd like some visual segregation of the different schema parts/modules?

**Comment by robross0606** [comment]
No visual segregation is needed, though that would be an interesting idea.  I'm just looking for a simple way to introspect the whole combined schema without having to concatenate them all manually into an intermediate file or script magic.

**Comment by NathanRSmith** [comment]
In addition to reading a single GraphQL SDL file, which is a newer feature, it can operate on the result of an introspection query. If you can access your endpoint, you should be able to point `graphqlviz` at it (perhaps with the `-a` flag to do auth header) to introspect the whole schema as presented by the server. Alternatively, you can get the introspection result yourself via `curl` or otherwise and pipe it to `graphqlviz`.

**Comment by robross0606** [comment]
That solution requires the server to be running live.  This is not a live endpoint, so introspection would be a more complicated solution that an intermediate file.  One relatively simple way to handle this might be to allow a schema to be piped into the tool, much like you expect your tool's output to be piped into dot:
```
cat *.graphql | graphqlviz -g -p | dot -Tpng > schema.png
```

**Comment by NathanRSmith** [comment]
That seems like a good solution, I created a more specific ticket in #22.

**Comment by sheerun** [comment]
Implemented in 3.1.0 by auto-detecting if schema is provided on stdin
