### ISSUE TITLE
Handle interface representation differently

### ISSUE THREAD

**Issue by robross0606** [sheerun/graphqlviz#24]
It would be nice to visually represent interfaces in a different manner.  If you have GraphQL schema with many types implementing the interface, the graph quickly gets out of control with spaghetti arrows all over the place.  A nice alternative representation would be to just put interfaces representations off to the side and put something like `Type :: Interface` in the title of types that implement the interface.  No arrows necessary.

**Comment by sheerun** [comment]
PR is welcome
