### ISSUE TITLE
Skip Relay option

### ISSUE THREAD

**Issue by glennr** [sheerun/graphqlviz#26]
First things first: thanks for building this! 

My question is: Do you have any plans to support a 'Skip Relay' option - like https://github.com/APIs-guru/graphql-voyager does? 

AFAICT it removes the intermediate Connections and Edges from the output graph, making Relay-compatible schemas a lot more readable.

Cheers.

**Comment by sheerun** [comment]
By myself no, but I'd accept a PR

**Comment by NathanRSmith** [comment]
As Sheerun noted, PRs are welcome. I have no experience with Relay at this time.
