### ISSUE TITLE
Fails on federated schema types

### ISSUE THREAD

**Issue by robross0606** [sheerun/graphqlviz#27]
Our schema relies on some federated types so we have something like this declared in our schema:
```
extend type User @key(fields: "id") {
  id: ID! @external
}
```
This is failing in graphqlviz with:
```
Unknown type "User".
Cannot extend type "User" because it is not defined.
Unknown directive "key".
Unknown directive "external".
```

**Comment by sheerun** [comment]
could you try to fix it?

**Comment by robross0606** [comment]
I figured out the issue.  I was exporting my schema prior to the output from `buildFederatedSchema` so it did not have the federation directive specs in it.
