### ISSUE TITLE
Holding back projects due to old version of GraphQL

### ISSUE THREAD

**Issue by robross0606** [sheerun/graphqlviz#30]
GraphQL is now at `15.4.0` but this project is holding things back at `14.7.0`

**Comment by NathanRSmith** [comment]
Could you elaborate? What issues are you encountering?

**Comment by robross0606** [comment]
We're encountering compatibility issues between using your tools in our project and using other tools which have progressed into the `^15.0.0` version.  If we include both, the included version is 14.7.0 and other tools have problems.

**Comment by robross0606** [comment]
I think this may be an issue of `npm` just completely borking lists of peer dependency conflicts.

**Comment by robross0606** [comment]
Now this is an actual issue.  Later versions of GraphQL support newer spec features like interfaces implementing other interfaces.  However, your project is still on GraphQL 14 which now breaks when handling a schema with newer features:
```
Syntax Error: Unexpected Name "implements"
```

**Comment by NathanRSmith** [comment]
I've been off in other lands. Do you expect that the newer graphql-js version (v16.4.0) introspection query will be incompatible with older server versions of GraphQL?

I assume this error is coming from using a local schema file which the older graphql-js version doesn't know how to parse properly?

**Comment by robross0606** [comment]
> Do you expect that the newer graphql-js version (v16.4.0) introspection query will be incompatible with older server versions of GraphQL?

I wouldn't think so.  Only the reverse is true.

> I assume this error is coming from using a local schema file which the older graphql-js version doesn't know how to parse properly?

That's correct.  I'm running against a locally parsed schema file.

**Comment by robross0606** [comment]
I'd be open to potentially doing a PR for this, but my other PR is still sitting with no feedback so I wasn't sure if I should bother.

**Comment by robross0606** [comment]
I've been trying to test a PR here using my fork and keep hitting this issue:
```
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: C:\Code\ncp\study-design-service\node_modules\meow\index.js
require() of ES modules is not supported.
require() of C:\Code\ncp\study-design-service\node_modules\meow\index.js from C:\Code\ncp\study-design-service\node_modules\graphqlviz\cli.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from C:\Code\ncp\study-design-service\node_modules\meow\package.json.
```
I suspect updating to `meow` 10 may have caused an ESM issue that wasn't revealed from unit tests (perhaps due to Ava Babel transcoding?).

**Comment by NathanRSmith** [comment]
Thanks again for your help. I believe v4.0.1 resolves this issue.
