### ISSUE TITLE
Add Mutations support

### ISSUE THREAD

**Issue by Glavin001** [sheerun/graphqlviz#4]
Looks like this line needs to be uncommented: https://github.com/sheerun/graphqlviz/blob/c1f7db88f07f2f9c73b5dbf2087cda396f216a97/index.js#L120

**Comment by marktani** [comment]
Is there a reason this is currently the case?

**Comment by NathanRSmith** [comment]
There is no mutation support because I have not implemented that in the project that motivated the initial efforts for graphqlviz. If somebody has a graph that supports mutations and wants to add that feature I would welcome pull requests. Thanks!

**Comment by rwe** [comment]
I've submitted a PR with a working implementation of this: sheerun/graphqlviz#11

**Comment by NathanRSmith** [comment]
Awesome @erydo I'll check it out this weekend! Unless @sheerun gets to it first

**Comment by sheerun** [comment]
Released 2.0.0 that fixes it, thanks @ajs139 !
