### ISSUE TITLE
Option to sort fields within entity

### ISSUE THREAD

**Issue by NathanRSmith** [sheerun/graphqlviz#6]
It would be nice to be able to sort fields within an entity.

**Comment by NathanRSmith** [comment]
@sheerun ready for release

**Comment by sheerun** [comment]
@NathanRSmith Could you fix CI issues first?

**Comment by NathanRSmith** [comment]
Sure, forgot about that

**Comment by sheerun** [comment]
@NathanRSmith Released. For the future, you also need to update README and CHANGELOG :)

**Comment by NathanRSmith** [comment]
Ha, my bad. Thanks for updating those.
