### ISSUE TITLE
handle non-null list types

### ISSUE THREAD

**Issue by yurigenin** [sheerun/graphqlviz#7]
Currently, any non-null lists ([Customer]!) or lists of non-null types ([Customer!]), or both ([Customer!]!) will show 'null' as type.

**Comment by NathanRSmith** [comment]
I am able to reproduce. Thanks for catching that.

**Comment by NathanRSmith** [comment]
@sheerun Please push new version to NPM when you get a chance

**Comment by NathanRSmith** [comment]
bump @sheerun
